-- ============================================================================
--  Publish With Vaishu — Database schema
--  Run this in the Supabase SQL editor BEFORE seed.sql.
--  (Generated by the build — not executed automatically.)
-- ============================================================================

-- Needed for gen_random_uuid()
create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
--  Enums
-- ----------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'order_status') then
    create type order_status as enum (
      'confirmed', 'processing', 'packed', 'shipped', 'delivered', 'cancelled'
    );
  end if;
end $$;

-- ----------------------------------------------------------------------------
--  users  (customer accounts — there is NO author login)
-- ----------------------------------------------------------------------------
create table if not exists users (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  email         text not null unique,
  password_hash text,
  phone         text,
  created_at    timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
--  authors  (admin-managed records; receive emails only)
-- ----------------------------------------------------------------------------
create table if not exists authors (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  email       text,
  phone       text,
  photo       text,            -- Cloudinary URL
  bio         text,
  designation text,
  department  text,
  college     text,
  created_at  timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
--  categories  (course / programme)
-- ----------------------------------------------------------------------------
create table if not exists categories (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  slug       text not null unique,
  created_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
--  books  (physical academic books only)
-- ----------------------------------------------------------------------------
create table if not exists books (
  id               uuid primary key default gen_random_uuid(),
  title            text not null,
  subtitle         text,
  isbn             text,
  edition          text,
  university       text,
  course           text,
  semester         text,
  language         text,
  pages            integer,
  publication_date date,
  price            numeric(10, 2) not null default 0,
  stock            integer not null default 0,
  cover_image      text,            -- Cloudinary URL
  description      text,
  is_featured      boolean not null default false,
  author_id        uuid references authors (id) on delete set null,
  category_id      uuid references categories (id) on delete set null,
  created_at       timestamptz not null default now()
);

create index if not exists books_category_idx on books (category_id);
create index if not exists books_author_idx on books (author_id);
create index if not exists books_featured_idx on books (is_featured);

-- ----------------------------------------------------------------------------
--  addresses
-- ----------------------------------------------------------------------------
create table if not exists addresses (
  id        uuid primary key default gen_random_uuid(),
  user_id   uuid not null references users (id) on delete cascade,
  full_name text,
  mobile    text,
  email     text,
  address   text,
  city      text,
  state     text,
  pincode   text,
  created_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
--  orders
-- ----------------------------------------------------------------------------
create table if not exists orders (
  id                  uuid primary key default gen_random_uuid(),
  order_number        text not null unique,   -- e.g. PWV-2026-0001
  user_id             uuid references users (id) on delete set null,
  subtotal            numeric(10, 2) not null default 0,
  shipping_charge     numeric(10, 2) not null default 0,
  grand_total         numeric(10, 2) not null default 0,
  status              order_status not null default 'confirmed',
  razorpay_payment_id text,
  razorpay_order_id   text,
  shipping_address    jsonb,                  -- snapshot at order time
  courier_name        text,
  tracking_number     text,
  tracking_url        text,
  created_at          timestamptz not null default now()
);

create index if not exists orders_user_idx on orders (user_id);

-- ----------------------------------------------------------------------------
--  order_items
-- ----------------------------------------------------------------------------
create table if not exists order_items (
  id             uuid primary key default gen_random_uuid(),
  order_id       uuid not null references orders (id) on delete cascade,
  book_id        uuid references books (id) on delete set null,
  title_snapshot text not null,
  price_snapshot numeric(10, 2) not null default 0,
  quantity       integer not null default 1
);

create index if not exists order_items_order_idx on order_items (order_id);

-- ----------------------------------------------------------------------------
--  reviews
-- ----------------------------------------------------------------------------
create table if not exists reviews (
  id         uuid primary key default gen_random_uuid(),
  book_id    uuid not null references books (id) on delete cascade,
  user_id    uuid references users (id) on delete set null,
  rating     integer not null check (rating between 1 and 5),
  comment    text,
  created_at timestamptz not null default now()
);

create index if not exists reviews_book_idx on reviews (book_id);

-- ============================================================================
--  Row Level Security
--  Public catalog data is world-readable (homepage uses the anon key).
--  Customer-private tables (users, addresses, orders, order_items) have RLS
--  enabled with NO public policy — they are reachable only via the service
--  role on the server in later milestones.
-- ============================================================================
alter table users        enable row level security;
alter table authors      enable row level security;
alter table categories   enable row level security;
alter table books        enable row level security;
alter table addresses    enable row level security;
alter table orders       enable row level security;
alter table order_items  enable row level security;
alter table reviews      enable row level security;

-- Public read policies for catalog tables.
drop policy if exists "public read categories" on categories;
create policy "public read categories" on categories for select using (true);

drop policy if exists "public read authors" on authors;
create policy "public read authors" on authors for select using (true);

drop policy if exists "public read books" on books;
create policy "public read books" on books for select using (true);

drop policy if exists "public read reviews" on reviews;
create policy "public read reviews" on reviews for select using (true);

-- ============================================================================
--  Trust statistics RPC
--  The homepage shows live counts of books / authors / students. Rather than
--  exposing the private `users` table to the anon key (which would leak
--  password_hash), we provide a SECURITY DEFINER function that returns ONLY
--  the aggregate counts. `users` itself stays fully locked down (no policy).
-- ============================================================================
create or replace function public.get_trust_stats()
returns table (
  books_published bigint,
  authors         bigint,
  students_served bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    (select count(*) from public.books)   as books_published,
    (select count(*) from public.authors) as authors,
    (select count(*) from public.users)   as students_served;
$$;

grant execute on function public.get_trust_stats() to anon, authenticated;
